// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Z-g4yvpL88wzME1Woe0n2Mrl9Z6SIUY',
    appId: '1:638695435234:web:3fbecb8e2f0cf96c86a7bb',
    messagingSenderId: '638695435234',
    projectId: 'live-tv-app-a884b',
    authDomain: 'live-tv-app-a884b.firebaseapp.com',
    storageBucket: 'live-tv-app-a884b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA32g412sEvnUo8WTG5ctV5lU5puzxYVCg',
    appId: '1:638695435234:android:3b5ec6f9919124f386a7bb',
    messagingSenderId: '638695435234',
    projectId: 'live-tv-app-a884b',
    storageBucket: 'live-tv-app-a884b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeKrl8g1k1Z7jKV1evrcLcwEGAggA_ZHM',
    appId: '1:638695435234:ios:ea0646cdee1f5b2a86a7bb',
    messagingSenderId: '638695435234',
    projectId: 'live-tv-app-a884b',
    storageBucket: 'live-tv-app-a884b.firebasestorage.app',
    iosBundleId: 'com.livewave.kurdlogs.liveWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Z-g4yvpL88wzME1Woe0n2Mrl9Z6SIUY',
    appId: '1:638695435234:web:cafca87670e70d3a86a7bb',
    messagingSenderId: '638695435234',
    projectId: 'live-tv-app-a884b',
    authDomain: 'live-tv-app-a884b.firebaseapp.com',
    storageBucket: 'live-tv-app-a884b.firebasestorage.app',
  );
}
